apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: spring-petclinic
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: spring-petclinic
spec:
  source:
    git:
      url: https://github.com/TanzuDK/spring-petclinic.git
      ref:
        branch: accelerator
        #tag: tap-1.2
